### ISSUE TITLE
CancellationTokenSource is not disposed in ServiceBusListener.ProcessMessageAsync and ServiceBusListener.ProcessSessionMessageAsync (possible memory leak)

### ISSUE THREAD

**Issue by andriiyaremenko** [Azure/azure-functions-servicebus-extension#104] opened 2020-08-13 14:24 UTC
Our Azure Function is under constant load lately and we found a memory leak.
After investigation, I found that the count of `Linked2CancellationTokenSource` in our heap tripled in just 15 minutes while our function was under heavy load. I searched through packages we use and found that `ServiceBusListener.ProcessMessageAsync` and `ServiceBusListener.ProcessSessionMessageAsync` creates `CancellationTokenSource` but does not dispose it. 

https://github.com/Azure/azure-functions-servicebus-extension/blob/8a01c68d16c5eeeda80010fd32f34d265eca9534/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L212

https://github.com/Azure/azure-functions-servicebus-extension/blob/8a01c68d16c5eeeda80010fd32f34d265eca9534/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L195

I'm not 100% sure that this is the source of our memory leak, though it looks like it. 
I would be very grateful if someone could confirm or refute my suspicion. 

If I am right I am ready to submit pull-request to fix it.

                                            --- UPDATE ---

I'm using macOS Catalina, version: 10.15.6

@joncanning created a test project that pooves there is a memory leak (you can find It here: https://github.com/andriiyaremenko/memory_leak_showcase_azure-functions-servicebus-extension)

if you run it you'll see that `CallbackNode  [System.Private.CoreLib.dll] `, `Linked2CancellationTokenSource  [System.Private.CoreLib.dll]` and `CallbackPartition  [System.Private.CoreLib.dll]` are not disposed and are growing in numbers over time:

##### This is top memory consumption objects before active message consumption
      6,070,128  GC Heap bytes
         77,677  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
512000 | 64 | 8000 | Grpc.Core.Internal.RequestCallCompletionDelegate  [Grpc.Core.dll]
388800 | 97200 | 4 | Entry<System.IntPtr,Grpc.Core.Internal.IOpCompletionCallback>[] (Bytes > 10K)
384000 | 48 | 8000 | Grpc.Core.Internal.RequestCallContextSafeHandle  [Grpc.Core.dll]
258190 | 51638 | 5 | System.Byte[] (Bytes > 10K)  [System.Private.CoreLib.dll]

##### This is top memory consumption objects during active message consumption
     43,037,449  GC Heap bytes
        548,482  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
16581440 | 80 | 207268 | CallbackNode  [System.Private.CoreLib.dll]
6630816 | 96 | 69071 | Linked2CancellationTokenSource  [System.Private.CoreLib.dll]
6082032 | 88 | 69114 | CallbackPartition[]  [System.Private.CoreLib.dll]
3871672 | 56 | 69137 | CallbackPartition  [System.Private.CoreLib.dll]
972816 | 312 | 3118 | System.Int32[]  [System.Private.CoreLib.dll]

##### This is top memory consumption objects immediately after active message consumption
     45,827,461  GC Heap bytes
        574,195  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
19205280 | 80 | 240066 | CallbackNode  [System.Private.CoreLib.dll]
7680192 | 96 | 80002 | Linked2CancellationTokenSource  [System.Private.CoreLib.dll]
7043960 | 88 | 80045 | CallbackPartition[]  [System.Private.CoreLib.dll]
4483808 | 56 | 80068 | CallbackPartition  [System.Private.CoreLib.dll]

##### This is top memory consumption objects minutes after active message consumption
     44,891,355  GC Heap bytes
        561,989  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
19205360 | 80 | 240067 | CallbackNode  [System.Private.CoreLib.dll]
7680192 | 96 | 80002 | Linked2CancellationTokenSource  [System.Private.CoreLib.dll]
7043960 | 88 | 80045 | CallbackPartition[]  [System.Private.CoreLib.dll]
4483808 | 56 | 80068 | CallbackPartition  [System.Private.CoreLib.dll]

Disposing `linkedCts` in `ProcessMessageAsync` and `_cancellationTokenSource` in `Dispose` fixes this memory leak:

##### This is top memory consumption objects during active message consumption
      7,732,187  GC Heap bytes
        102,285  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
512000 | 64 | 8000 | Grpc.Core.Internal.RequestCallCompletionDelegate  [Grpc.Core.dll]
388800 | 97200 | 4 | Entry<System.IntPtr,Grpc.Core.Internal.IOpCompletionCallback>[] (Bytes > 10K)  [System.Private.CoreLib.dll]
384000 | 48 | 8000 | Grpc.Core.Internal.RequestCallContextSafeHandle  [Grpc.Core.dll]
380016 | 312 | 1218 | System.Int32[]  [System.Private.CoreLib.dll]

##### This is top memory consumption objects immediately after active message consumption
      6,731,729  GC Heap bytes
         85,950  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
512000 | 64 | 8000 | Grpc.Core.Internal.RequestCallCompletionDelegate  [Grpc.Core.dll]
388800 | 97200 | 4 | Entry<System.IntPtr,Grpc.Core.Internal.IOpCompletionCallback>[] (Bytes > 10K)  [System.Private.CoreLib.dll]
384000 | 48 | 8000 | Grpc.Core.Internal.RequestCallContextSafeHandle  [Grpc.Core.dll]
309828 | 51638 | 6 | System.Byte[] (Bytes > 10K)  [System.Private.CoreLib.dll]

##### This is top memory consumption objects minutes after active message consumption
      6,653,359  GC Heap bytes
         84,070  GC Heap objects

Total Memory | Object Bytes | Count | Type
-- | -- | -- | --
512000 | 64 | 8000 | Grpc.Core.Internal.RequestCallCompletionDelegate  [Grpc.Core.dll]
388800 | 97200 | 4 | Entry<System.IntPtr,Grpc.Core.Internal.IOpCompletionCallback>[] (Bytes > 10K)  [System.Private.CoreLib.dll]
384000 | 48 | 8000 | Grpc.Core.Internal.RequestCallContextSafeHandle  [Grpc.Core.dll]
361466 | 51638 | 7 | System.Byte[] (Bytes > 10K)  [System.Private.CoreLib.dll]

This fix works on macOS and @joncanning is still validating my result for Windows platform.

I'm submitting my pull-request. 
I hope I did everything right and in accordance with your contribution guides.

**Comment by Blackbaud-IanThomas** [comment] 2020-08-31 15:11
@brettsam My team has been seeing what seem like memory leaks when running at high load in production, as well.  We would be very interested in getting this memory leak fixed to see if that solves our problems.

**Comment by sidkri** [comment] 2020-09-02 22:11
@pragnagopa  I have assigned this to myself for analysis.  Will update the sprint once I know what needs to be done.  Thanks for surfacing.

**Comment by Blackbaud-IanThomas** [comment] 2020-09-15 18:15
@sidkri Do we have an update on this one?

**Comment by fabiocav** [comment] 2020-09-16 20:19
@sidkri FYI, moving this to sprint 85, but please let us know if you need that changed.

**Comment by sidkri** [comment] 2020-09-17 05:50
@Blackbaud-IanThomas, sorry for not responding sooner.  I am working on a code change (#102 ) and will incorporate disposing of the CancellationTokenSource as part of the change.  Not sure if its responsible for the memory growth but it should definitely be disposed.  We will try to look into possible memory leaks following that.

**Comment by Blackbaud-IanThomas** [comment] 2020-09-17 11:12
@sidkri Thanks for the update! I’ll follow the related issue as well and keep an eye on when this is released.

**Comment by sidkri** [comment] 2020-09-21 06:36
This is addressed in PR: #102

**Comment by sidkri** [comment] 2020-09-23 03:42
The PR #102 addresses this and is merged and will be released as part of 4.0.2 shortly.  Resolving this issue now.  Thanks for surfacing the potential issue.

**Closed by sidkri** 2020-09-23 03:42 UTC

**Comment by Blackbaud-IanThomas** [comment] 2020-09-24 15:16
@sidkri I'm not sure where the best place to bring this up is, on this issue or another, but even after updating to use the latest version of the service bus extensions, we are seeing continual memory growth under load.  Seeing your comment
> We will try to look into possible memory leaks following that.
We are definitely still interested in that and would value help identifying the root cause of the issue.  The issue has been consistently appearing in all webjobs we have that consume service bus messages, particularly with a high volume.

**Comment by JonCanning** [comment] 2020-09-24 15:51
This has solved our issue
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/671232/94168906-0ae3de80-fe86-11ea-840e-fc6bb8c0913e.png">

**Comment by sidkri** [comment] 2020-09-24 18:47
@Blackbaud-IanThomas , my recommendation is to open a support ticket and reference this issue.  Our support team can work with you interactively to get details of your resources so we can investigate in more depth. They will get in touch with the product team to investigate further. It appears your issue might be different from what was highlighted here.

**Comment by sidkri** [comment] 2020-09-24 18:49
@andriiyaremenko and @JonCanning , thank you for your efforts in surfacing this issue and the fix!  I incorporated the fix in my branch to save on validation and review time, contributions are welcome.

**Comment by andriiyaremenko** [comment] 2020-09-25 07:37
@sidkri, we are happy to help!
