### ISSUE TITLE
Version 4.1.0 no longer works with custom serialization

### ISSUE THREAD

**Issue by tomgallard** [Azure/azure-functions-servicebus-extension#52] opened 2020-01-23 13:58 UTC
- Our solution uses our own serialization to write/read a byte[] of data into a Microsoft.Azure.ServiceBus.Message .
- After upgrading the Microsoft.Azure.WebJobs.Extensions.Service bus package to 4.1.0 we started receiving the following errors when a message was received:

`Exception while executing function: ReceiveScheduledTask One or more errors occurred. Exception binding parameter 'rawMessage' The Message with ContentType 'null' failed to deserialize to a string with the message: 'Expecting element 'string' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/'.. Encountered 'Element'  with name 'ScheduledTaskMessage', namespace 'http://schemas.datacontract.org/2004/07/CFS.PhotoPrintApi.BackgroundService.Queueing'. ' Expecting element 'string' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/'.. Encountered 'Element'  with name 'ScheduledTaskMessage', namespace 'http://schemas.datacontract.org/2004/07/CFS.PhotoPrintApi.BackgroundService.Queueing'.  Exception binding parameter 'messageReceiver' Binding data does not contain expected value 'messageReceiver'. `

We have tried this with both ContentType null and on setting the Message.ContentType to application/octet-stream , which results in much the same error.

I suspect this is related to[ this commit](https://github.com/Azure/azure-functions-servicebus-extension/commit/4c4ef3252112bc822a5c80a26824b12146330650) adding batch support

We have resolved by rolling back nuget package version- but would be good to know if the underlying cause is a bug, or if we are doing something wrong our end.

thanks

**Comment by alrod** [comment] 2020-01-24 02:35
@tomgallard, can you please share your ServiceBus function code?

**Comment by tomgallard** [comment] 2020-01-24 09:29
Sure- though unable to supply all of it- as a rather big solution- here are the bits that feel most relevant:

Trigger signature:
`[ServiceBusAccount("WebJob-ServiceBusConnectionString")]
        [FunctionName("ReceiveScheduledTask")]
        [Disable("Environment:IsStaging")]
        public async Task Receive(
            [ServiceBusTrigger("%scheduledtaskqueuename%")]
        Message rawMessage, MessageReceiver messageReceiver, CancellationToken token)`

Message creation:

`  Message message = new Message(QueueMessage<T>.EncodeObject(objectToWrite));`

Encode object function:

`
public static byte[] EncodeObject(T objectToEncode)
        {

            var ser = new DataContractSerializer(typeof(T));
            using (var ms = new MemoryStream())
            {
                using (XmlDictionaryWriter binaryDictionaryWriter = XmlDictionaryWriter.CreateBinaryWriter(ms))
                {
                    ser.WriteObject(binaryDictionaryWriter, objectToEncode);
                }
                return ms.ToArray();
            }
        }
`

**Comment by alrod** [comment] 2020-01-24 23:13
Closed as duplicate of #48

**Closed by alrod** 2020-01-24 23:13 UTC
